title: Thank you for the Overwhelming Support for NDP 2024!
url: https://ndp.gov.sg
favicon: /images/august 9 svg.svg
colors:
  primary-color: "#bc2327"
  secondary-color: "#eb202c"
  media-colors:
    - title: media-color-one
      color: "#211f1f"
    - title: media-color-two
      color: "#bc2327"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: We look forward to celebrating NDP 2025 with you! Stay tuned for
  when this page relaunches.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.djipm54x1o4t0.amplifyapp.com
prod: https://master.d1j88xoid2xj7c.amplifyapp.com
facebook-pixel: ""
shareicon: /images/august 9.png
is_government: true
google_analytics_ga4: ""
linkedin-insights: ""
